services:
    smtp-project:
        build:
            dockerfile: Dockerfile
        ports:
            - "2525:2525"
        volumes:
            - .:/app
        environment:
            - PYTHONUNBUFFERED=1
        networks:
            - constructionAutomation

networks:
  constructionAutomation:
    external: true