version: '3.8'

services:
  smtp-project:
    container_name: smtp_service_1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2525:2525"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - constructionAutomation


  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - constructionAutomation
      
networks:
  constructionAutomation:
    external: true
    
volumes:
  pgdata: